### ISSUE TITLE
issues running sudo systemctl enable skyweather2

### ISSUE THREAD

**Issue by mauriceatkinson** [maccampb/SkyWeather2Daemons#1]
I am obviously doing something wrong as when I follow your steps and run sudo systemctl enable skyweather2  I get the following error message:

pi@skyweather2:~ $ sudo systemctl enable skyweather2
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.

Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
pi@skyweather2:~ $

**Comment by maccampb** [comment]
Hi.. sorry you're running into an issue...

Let's get some data to see what's happening...

Could you run the following commands

sudo uname -a
sudo systemctl status skyweather2
sudo systemctl --version
cat /etc/os-release

And paste the outputs here?

Can you copy and paste the contents of the two files you copied to

/etc/systemd/system into your reply?

Thanks!

**Comment by mauriceatkinson** [comment]
Dont apologise for the issue as I am just glad someone has provided the code to run skyweather as a service!!

Your reply stating which two files copied into the /etc/systemd/system directory rings alarm bells as I only copied one file as shown below.

`pi@skyweather2:~/SDL_Pi_SkyWeather2 $ sudo uname -a
Linux skyweather2 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`

`pi@skyweather2:~/SDL_Pi_SkyWeather2 $ sudo systemctl status skyweather2
● skyweather2.service - Service File to manage the skyweather2 service
   Loaded: loaded (/etc/systemd/system/skyweather2.service; static; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2022-05-31 19:00:26 BST; 2s ago
  Process: 5798 ExecStart=/home/pi/bin/skyweather2exec.sh (code=exited, status=203/EXEC)
 Main PID: 5798 (code=exited, status=203/EXEC)`

`pi@skyweather2:~/SDL_Pi_SkyWeather2 $ sudo systemctl --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid`

`pi@skyweather2:~/SDL_Pi_SkyWeather2 $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

The only file I copied into the /etc/systemd/system was skyweather2.service:
`# skyweather2.service
[Unit]
Description=Service File to manage the skyweather2 service
After=network.target
After=mysqld.service

[Service]
Type=idle
ExecStart=/home/pi/bin/skyweather2exec.sh
WorkingDirectory=/home/pi/SDL_Pi_SkyWeather2
Restart=always
RestartSec=10
User=root
Requires=multi-user.target

[Install]
# WantedBy=multi-user.target`

The file skyweather2exec.sh was copied into the same directory as SkyWeather2.py
`#! /bin/bash
#
# file: skyweather2exec.sh
# used as part of the systmed setup to run the SkyWeather2 python app as a service.
#
cd /home/pi/SDL_Pi_SkyWeather2
/usr/bin/python3 /home/pi/SDL_Pi_SkyWeather2/SkyWeather2.py >> /home/pi/SDL_Pi_skyweather2.out 2>&1
# /usr/bin/python3 /home/pi/SDL_Pi_SkyWeather2/SkyWeather2.py > /dev/null 2>&1`

**Comment by maccampb** [comment]
my skyweather2exec.sh is located in /home/pi/bin...

```
pi@SwitchDocLabs:~/bin $ pwd
/home/pi/bin
pi@SwitchDocLabs:~/bin $ ls -la
total 20
drwxr-xr-x  2 pi pi 4096 Nov 25  2021 .
drwxr-xr-x 41 pi pi 4096 May 31 00:21 ..
-rwxr-xr-x  1 pi pi  331 Nov 25  2021 dashboard.sh
-rw-------  1 pi pi   79 Nov 21  2021 nohup.out
-rwxr-xr-x  1 pi pi  225 Nov 25  2021 skyweather2exec.sh
pi@SwitchDocLabs:~/bin $
```

check that the skyweather2exec.sh is located there and is executable. 

```
pi@SwitchDocLabs:~/bin $ ls -la *exec*
-rwxr-xr-x 1 pi pi 225 Nov 25  2021 skyweather2exec.sh
```

i will check if my instructions tell you to put in the /home/pi/bin directory...


you can make it executable by running 

`chmod +x skyweather2exec.sh`

**Comment by mauriceatkinson** [comment]
thanks I have tried the new instructions but still get an error.  

`pi@skyweather2:~ $ sudo systemctl enable skyweather2
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.

Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
pi@skyweather2:~ $`

`pi@skyweather2:~/bin $ ls -la
total 12
drwxr-xr-x  2 pi pi 4096 Jun  1 08:04 .
drwxr-xr-x 45 pi pi 4096 Jun  1 08:02 ..
-rwxr-xr-x  1 pi pi  338 May 31 10:21 skyweather2exec.sh`

`pi@skyweather2:~ $ sudo systemctl status skyweather2
● skyweather2.service - Service File to manage the skyweather2 service
   Loaded: loaded (/etc/systemd/system/skyweather2.service; static; vendor preset: enabled)
   Active: active (running) since Wed 2022-06-01 08:02:52 BST; 8min ago
 Main PID: 13350 (skyweather2exec)
    Tasks: 28 (limit: 4915)
   CGroup: /system.slice/skyweather2.service
           ├─13350 /bin/bash /home/pi/bin/skyweather2exec.sh
           ├─13351 /usr/bin/python3 /home/pi/SDL_Pi_SkyWeather2/SkyWeather2.py
           ├─13374 /usr/bin/pigpiod
           └─13390 /usr/local/bin/rtl_433 -q -M level -F json -R 146 -R 147 -R 148 -R 150 -R 151 -R 152 -R 153

Jun 01 08:02:52 skyweather2 systemd[1]: Started Service File to manage the skyweather2 service.
Jun 01 08:02:56 skyweather2 systemd[1]: /etc/systemd/system/skyweather2.service:12: Unknown lvalue 'Requires' in section 'Ser
Jun 01 08:03:10 skyweather2 systemd[1]: /etc/systemd/system/skyweather2.service:12: Unknown lvalue 'Requires' in section 'Ser
Jun 01 08:04:25 skyweather2 systemd[1]: /etc/systemd/system/skyweather2.service:12: Unknown lvalue 'Requires' in section 'Ser
Jun 01 08:04:49 skyweather2 systemd[1]: /etc/systemd/system/skyweather2.service:12: Unknown lvalue 'Requires' in section 'Ser
Jun 01 08:07:24 skyweather2 systemd[1]: /etc/systemd/system/skyweather2.service:12: Unknown lvalue 'Requires' in section 'Ser
Jun 01 08:08:32 skyweather2 systemd[1]: /etc/systemd/system/skyweather2.service:12: Unknown lvalue 'Requires' in section 'Ser
lines 1-18/18 (END)`

**Comment by maccampb** [comment]
So the good news is it looks like it’s running with all the correct services. 

Are you seeing the updates in the database?

It looks like the service file is damaged. Can you send a text file with the contents of the skyweather2.service file?

Regards,

MAC

www.ckmmconsulting.ca
Via iPhone 12.

**Comment by maccampb** [comment]
I've tweaked the skyweather2.service to eliminate the error messages. Please down load and let me know if that works...

**Comment by mauriceatkinson** [comment]
that has done the trick as it is working now.  thanks very much

**Comment by maccampb** [comment]
Thank you for helping me get it right. 

I will close the issue over the next few days. 

Regards,

MAC

www.ckmmconsulting.ca
Via iPhone 12.
